apiVersion: apps/v1
kind: Deployment
metadata:
  name: med-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: med-web
  template:
    metadata:
      labels:
        app: med-web
    spec:
      containers:
      - name: med-web
        image: medicleshub.azurecr.io/ramazankilimciswe573project_promed:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "512Mi"
            cpu: "1"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: med-web
spec:
  type: LoadBalancer
  selector:
    app: med-web
  ports:
  - port: 80

