trigger:
- main

pool: Default

steps:
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Dev Subscription(0d35d4f7-c9bd-4b00-ab26-a9e337fb683a)'
    azureContainerRegistry: '{"loginServer":"medicleshub.azurecr.io", "id" : "/subscriptions/0d35d4f7-c9bd-4b00-ab26-a9e337fb683a/resourceGroups/rg-medicles/providers/Microsoft.ContainerRegistry/registries/medicleshub"}'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Run services'
  displayName: 'Run docker containers'

- task: UsePythonVersion@0
  inputs:
    versionSpec: 3.9.5
    architecture: 'x64'
  displayName: 'Use Python version'

- script: |
    python3.9 -m pip install --upgrade pip setuptools wheel
    pip3.9 install -r requirements.txt
    pip3.9 install -r requirements-test.txt
    sudo apt-get install -y gettext
  displayName: 'Install prerequisites'

- script: |
    pushd '$(projectRoot)'
    python3.9 manage.py test --testrunner xmlrunner.extra.djangotestrunner.XMLTestRunner --no-input
  continueOnError: true
  displayName: 'Run tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'
  displayName: 'Publish test results'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish build artifacts'
