apiVersion: apps/v1
kind: Deployment
metadata:
  name: med-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: med-web
  template:
    metadata:
      labels:
        app: med-web
    spec:
      containers:
      - name: med-web
        image: medicleshub.azurecr.io/ramazankilimciswe573project_promed:latest
        imagePullPolicy: Always
        command: ["/bin/bash", "-c"]
        args: ["python manage.py migrate; gunicorn pubmed_project.wsgi:application --bind 0.0.0.0:8000"]
        resources:
          limits:
            memory: "512Mi"
            cpu: "0.2"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: med-web
spec:
  type: LoadBalancer
  selector:
    app: med-web
  ports:
  - port: 80
    targetPort: 8000