# Generated by Django 3.1.1 on 2021-06-08 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicles', '0002_article_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_key', models.CharField(blank=True, max_length=100, null=True)),
                ('tag_value', models.CharField(blank=True, max_length=100, null=True)),
                ('article', models.ManyToManyField(to='medicles.Article')),
            ],
        ),
    ]
