# Generated by Django 3.1.1 on 2021-06-10 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicles', '0003_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
    ]
