# Generated by Django 3.1.1 on 2021-06-16 08:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicles', '0004_remove_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
