# Generated by Django 3.1.1 on 2021-06-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicles', '0005_auto_20210616_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.TextField(blank=True, null=True),
        ),
    ]
